Algoritmo "calculando sua media"

Var
// Seção de Declarações das variáveis 
nome:caractere
media, nota1, nota2 : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreval ("calculando media")
      escreval ("qual seu nome")
      leia(nome)
      escreval ("qual sua nota 1?")
      leia(nota1)
      escreval ("qual sua nota 2?")
      leia(nota2)
      media <- (nota1 + nota2) /2
      escreval ("sua media é ", media)
      


Fimalgoritmo