Algoritmo "conversão  "

Var
// Seção de Declarações das variáveis 
valorReal, valorDolar, conversao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      escreval ("digite o valor em real")
      leia (valorReal)
      escreval("qual o atual preço do dolar?")
      leia(valorDolar)
      conversao <- valorReal/valorDolar
      escreval ("o total em dolar é: " ,conversao)

Fimalgoritmo